config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "restaurants#index"
  get "/restaurants/:id/kitchen", to: "restaurants#kitchen", as: "kitchen"
  get "/restaurants/:restaurant_id/users/:user_id/table_orders", to: "table_orders#server", as: "server"
  get "/order_items/:id/prepared", to: "order_items#prepared!", as: "prepared"
  get "/order_items/:id/served", to: "order_items#served!", as: "served"
  get "/table_customers/:id/ordered", to: "table_customers#ordered!", as: "ordered"
  # get "restaurants/:id/tables/:table_id/table_orders/:table_order_id/checkout", to: "table_orders#checkout", as: "checkout"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/checkout", to: "table_customers#checkout", as: "checkout"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/confirmation", to: "table_customers#confirmation", as: "confirmation"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :join_menus, only: :destroy
  resources :order_items, only: :destroy
  resources :restaurants do
    resources :restaurant_servers
    resources :menu_items
    resources :menus do
      resources :join_menus, only: %i[show new create]
    end
    resources :tables do
      resources :table_orders do
        resources :table_customers do
          resources :order_items
        end
      end
    end
  end
  get "restaurants/:restaurant_id/menus/:id/activated", to: "menus#activated!", as: "activated"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/split_evenly", to: "table_customers#split_evenly", as: "split_evenly"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/split_by_items", to: "table_customers#split_by_items", as: "split_by_items"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/pay_all", to: "table_customers#pay_all", as: "pay_all"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/card_roulette", to: "table_customers#card_roulette", as: "card_roulette"
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :restaurant
  has_many :join_menus, dependent: :destroy
  has_many :menu_items, through: :join_menus
  has_one_attached :photo

  validates :name, presence: true
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_restaurant, only: %i[index show new create edit update destroy activated!]
  before_action :set_menu, only: %i[show edit update destroy activated!]

  def index
    @menus = Menu.all
  end

  def show
    @join_menus = @menu.join_menus
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    @menu.is_active = true if @restaurant.menus.count.zero?
    @menu.restaurant = @restaurant
    if @menu.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # We might also need an edit method TBD
  end

  def update
    @menu.update(menu_params)
    redirect_to restaurant_menu_path(@restaurant, @menu)
  end

  def destroy
    @menu.destroy
    redirect_to restaurant_path(@menu.restaurant), status: :see_other
  end

  def activated!
    @menus = Menu.all
    @menus.each do |menu|
      menu.update(is_active: false)
    end
    @menu.update(is_active: true)
    redirect_to restaurant_menu_path(@restaurant, @menu)
  end

  private

  def menu_params
    params.require(:menu).permit(:name, :photo)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def set_menu
    @menu = Menu.find(params[:id])
  end
end

app/views/menus/_form.html.erb
<%= simple_form_for [restaurant, menu] do |f| %>
  <div>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
  </div>
  <div class="flex justify-start items-center pt-8">
    <div class="flex justify-center items-center h-10 rounded-lg bg-black">
      <%= f.submit menu.id.nil? ? "Create" : "Save", class: "text-xl mx-8 text-white" %>
    </div>
  </div>
<% end %>

app/views/menus/_index.html.erb
<div class="w-1/3 bg-white rounded-lg h-min">
  <div class="m-8">
    <h2 class="text-xl font-bold mb-3">Menus</h2>

    <div class="flex-wrap content-start overflow-auto scroll-container">
      <%# if is_active is true %>
        <% active_menu = Menu.where(restaurant_id: restaurant.id).select(&:is_active).first %>
        <% unless active_menu.nil? %>
          <%= link_to restaurant_menu_path(restaurant, active_menu) do  %>
            <div>
              <% if active_menu.photo.attached? %>
                <%= cl_image_tag active_menu.photo.key, height: 150, width: 400, crop: :fill, class: "d-block rounded-lg"%>
              <% else %>
                <img src=<%= "https://source.unsplash.com/random/400x150/?restaurant-1" %> class="d-block rounded-lg" alt="restaurant image">
              <% end %>
            </div>
            <div class="flex justify-between items-center">
              <div class="bg-green-500 text-sm text-white rounded-lg px-3 py-0.5">Active</div>
              <p class="text-right text-lg font-bold mt-1"><%= active_menu.name %></p>
            </div>

          <% end %>
        <% end %>
      <% menus.each do |menu| %>
        <div class="mt-4">
          <%# if is_active is false %>
          <% if menu.is_active == false %>
            <%= link_to restaurant_menu_path(restaurant, menu) do  %>
              <div>
                <% if menu.photo.attached? %>
                  <%= cl_image_tag menu.photo.key, height: 150, width: 400, crop: :fill, class: "d-block rounded-lg" %>
                <% else %>
                  <img src=<%= "https://source.unsplash.com/random/400x150/?restaurant-#{menu.id}" %> class="d-block rounded-lg" alt="restaurant image">
                <% end %>
              </div>
              <p class="text-right text-lg font-bold mt-1"><%= menu.name %></p>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="flex justify-center items-center bg-white rounded-bl-lg rounded-br-lg p-8 border-t border-black z-10">
    <%= link_to new_restaurant_menu_path(restaurant) do %>
      <div class="flex justify-center items-center w-10 h-10 rounded-full bg-black">
        <i class="fa-solid fa-plus text-white"></i>
      </div>
    <% end %>
  </div>
</div>

app/views/menus/_show.html.erb
<div class="page-container pt-8">
  <div class="flex">
    <div class="p-3 border mr-3">
      <%= link_to "Back", restaurant_path(@restaurant) %>
    </div>
    <div class="p-3 border mr-3">
      <%= link_to "Edit", edit_restaurant_menu_path(@restaurant, @menu) %>
    </div>
    <div class="p-3 border">
      <%= link_to "Delete", restaurant_menu_path(@restaurant, @menu), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </div>

  </div>
  <%= render "join_menus/item", menu: @menu %>
</div>

app/views/menus/edit.html.erb
<div class="page-container pt-8">
  <div class="flex items-center justify-between mb-8">
    <div class="w-48">
      <%= link_to restaurant_path(@restaurant) do %>
        <i class="fa-solid fa-chevron-left"></i>
      <% end %>
    </div>

    <h2 class="text-xl font-bold">Edit Menu</h2>
    <div class="flex justify-end w-48"></div>
  </div>

  <%= simple_form_for [@restaurant, @menu] do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
    </div>

    <div class="flex justify-start items-center pt-8">
      <div class="flex justify-center items-center h-10 rounded-lg bg-black form-actions">
        <%= f.button :submit, class: "text-xl font-bold mx-8 text-white" %>
      </div>
    </div>
  <% end %>
</div>

app/views/menus/new.html.erb
<div class="page-container pt-8">
  <div class="flex items-center justify-between mb-8">
    <div class="w-48">
      <%= link_to restaurant_path(@restaurant) do %>
        <i class="fa-solid fa-chevron-left"></i>
      <% end %>
    </div>
    <h2 class="text-xl font-bold">New Menu</h2>
    <div class="w-48"></div>
  </div>
  <%= render "menus/form", restaurant: @restaurant, menu: @menu %>
</div>

app/views/menus/show.html.erb
<div class="page-container pt-8">
  <div class="flex items-center justify-between mb-4">
    <%= link_to restaurant_path(@restaurant) do %>
      <i class="fa-solid fa-chevron-left"></i>
    <% end %>

    <div class="flex justify-end gap-3">
      <% if @menu.is_active == false %>
        <%= link_to activated_path(@restaurant, @menu), class:"bg-green-500 flex justify-center items-center text-sm text-white rounded-lg px-4 py-2" do %>
          <h2>Activate Menu</h2>
        <% end %>
      <% end %>
      <div>
        <%= link_to restaurant_menu_path(@restaurant, @menu), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:"bg-red-400 flex justify-center items-center text-sm text-white rounded-lg px-4 py-2" do %>
          <h2>Delete Menu</h2>
        <% end %>
      </div>
    </div>
  </div>

  <div class="w-full bg-white rounded-lg">
    <div class="p-8">
      <div class="flex gap-3 mb-3">
        <h2 class="text-xl font-bold"><%= @menu.name %></h2>
        <% if @menu.is_active %>
          <div class="bg-green-500 flex justify-center items-center text-sm text-white rounded-lg px-3 py-1">
            <p>Active</p>
          </div>
        <% end %>
      </div>

      <div class="scroll-container overflow-auto">
        <% categories = ["Ramen", "Izakaya", "Rice Dishes", "Vegetarian", "Gluten Free", "Desserts", "Drinks"] %>
        <% categories.each do |category| %>
          <% menu = @menu.menu_items.select { |item| item.category == category } %>
            <% unless menu.empty? %>
              <h3 class="text-lg font-bold mb-3 mt-8"><%= category %></h3>
              <%= render "menu_items/show", menu: menu %>
            <% end %>
        <% end %>
      </div>
    </div>

    <div class="flex justify-center items-center bg-white rounded-bl-lg rounded-br-lg p-8 border-t border-black z-10">
      <%= link_to new_restaurant_menu_join_menu_path(@restaurant, @menu) do %>
        <div class="flex justify-center items-center h-10 rounded-lg bg-black">
          <h2 class="text-xl font-bold mx-8 text-white">Add Items</h2>
        </div>
      <% end %>
    </div>
  </div>
</div>