config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "restaurants#index"
  get "/restaurants/:id/kitchen", to: "restaurants#kitchen", as: "kitchen"
  get "/restaurants/:restaurant_id/users/:user_id/table_orders", to: "table_orders#server", as: "server"
  get "/order_items/:id/prepared", to: "order_items#prepared!", as: "prepared"
  get "/order_items/:id/served", to: "order_items#served!", as: "served"
  get "/table_customers/:id/ordered", to: "table_customers#ordered!", as: "ordered"
  # get "restaurants/:id/tables/:table_id/table_orders/:table_order_id/checkout", to: "table_orders#checkout", as: "checkout"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/checkout", to: "table_customers#checkout", as: "checkout"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/confirmation", to: "table_customers#confirmation", as: "confirmation"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :join_menus, only: :destroy
  resources :order_items, only: :destroy
  resources :restaurants do
    resources :restaurant_servers
    resources :menu_items
    resources :menus do
      resources :join_menus, only: %i[show new create]
    end
    resources :tables do
      resources :table_orders do
        resources :table_customers do
          resources :order_items
        end
      end
    end
  end
  get "restaurants/:restaurant_id/menus/:id/activated", to: "menus#activated!", as: "activated"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/split_evenly", to: "table_customers#split_evenly", as: "split_evenly"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/split_by_items", to: "table_customers#split_by_items", as: "split_by_items"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/pay_all", to: "table_customers#pay_all", as: "pay_all"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/card_roulette", to: "table_customers#card_roulette", as: "card_roulette"
end

app/models/table_order.rb
class TableOrder < ApplicationRecord
  belongs_to :table
  belongs_to :user
  has_many :table_customers
  has_many :order_items, through: :table_customers
  has_one :restaurant, through: :table
end

app/controllers/table_orders_controller.rb
class TableOrdersController < ApplicationController
  before_action :set_table_order, only: [:show, :edit, :update, :destroy]
  before_action :set_restaurant, only: [:server, :new, :create]
  before_action :set_table, only: [:new, :create]

  def index
    @table_orders = TableOrder.all
  end

  def server
    @table_orders = TableOrder.where(user_id: params[:user_id])
  end

  def show
    @table_orders = TableOrder.find(params[:id])
  end

  def new
    if @table.table_orders.any?(&:is_active)
      @table_order = TableOrder.find_by(is_active: true)
      redirect_to new_restaurant_table_table_order_table_customer_path(@restaurant, @table, @table_order)
    else
      @table_order = TableOrder.new
    end
  end

  # def checkout
  #   @table_order = TableOrder.find(params[:id])
  #   @restaurant = @table_order.restaurant
  #   @table = @table_order.table
  #   # order  = Order.create!(teddy: teddy, teddy_sku: teddy.sku, amount: teddy.price, state: 'pending', user: current_user)
  #   table_price = 0

  #   @table_order.order_items.each do |order|
  #    table_price += order.menu_item.price
  #   end

  #   session = Stripe::Checkout::Session.create(
  #     payment_method_types: ['card'],
  #     line_items: [{
  #       price_data: {
  #         currency: 'usd',
  #         unit_amount: table_price.to_i * 100,
  #         product_data: {
  #           name: 'T-shirt',
  #           description: 'Comfortable cotton t-shirt',
  #           images: ['https://example.com/t-shirt.png'],
  #         },
  #       },
  #       quantity: 1,
  #     }],
  #     mode: 'payment',
  #     success_url: "http://127.0.0.1:3000/restaurants/#{@restaurant.id}/tables/#{@table.id}/table_orders/#{@table_order.id}/confirmation",
  #     cancel_url: "http://127.0.0.1:3000/restaurants/#{@restaurant.id}/tables/#{@table.id}/table_orders/#{@table_order.id}/checkout",
  #   )

  #   @table_order.update(checkout_session_id: session.id)
  #   # redirect_to checkout_path(@restaurant, @table, @table_order)
  # end

  def create
    @table_order = TableOrder.new(table_order_params)
    @table_order.is_active = true
    # @table_order.is_active = true if params[:table_order][:is_active] == "false"

    @table_order.user = User.find_by(first_name: "Mario")
    @table_order.table = @table
    if @table_order.save
      @table.update(is_active: true)
      redirect_to new_restaurant_table_table_order_table_customer_path(@restaurant, @table, @table_order)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @table_order = TableOrder.new
  end

  def update
    @table_order.update(table_order_params)
    redirect_to table_order_path(@table_order)
  end

  def destroy
    @table_order.destroy
    redirect_to table_orders_path, status: :see_other
  end

  private

  def set_table_order
    @table_order = TableOrder.find(params[:id])
  end

  def set_table
    @table = Table.find(params[:table_id])
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def table_order_params
    # Needs work
    params.require(:table_order).permit(:is_active)
  end
end

app/views/table_orders/_show.html.erb
<% table_order = table_orders.where(table_id: table.id).select { |order| order.is_active }.first %>
<h4 class="font-bold"><%= link_to table.table_number, restaurant_table_table_order_path(restaurant, table, table_order) %></h4>

app/views/table_orders/new.html.erb
<div class="landing-background w-screen h-screen">
  <div class="customer-container-landing h-full flex flex-col justify-between">
    <div class="w-full h-10"></div>
    <h2 class="flex w-full justify-center items-center text-3xl font-bold"><%= @restaurant.name %></h2>
    <h2 class="flex w-full justify-center items-center text-xl font-bold">Table <%= @table.table_number %></h2>

    <%= simple_form_for [@restaurant, @table, @table_order] do |f| %>
      <%= f.input :is_active, as: :hidden, default: true %>
      <%= f.submit "Create Order", class: "flex w-full justify-center items-center h-10 rounded-lg bg-black text-lg font-bold text-white" %>
    <%  end %>
  </div>
</div>

app/views/table_orders/server.html.erb
<div class="page-container pt-8">

  <% if user_signed_in?%>

    <div class="flex justify-between items-center mb-8">
      <div class="w-24">
        <%= link_to restaurant_path(@restaurant) do %>
          <i class="fa-solid fa-chevron-left"></i>
        <% end %>
      </div>
      <h2 class="text-center text-xl font-bold"><%= current_user.first_name %></h2>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "flex justify-end items-center w-24" %>
    </div>

    <div class="w-full bg-white rounded-lg">
      <% current_user.table_orders.each do |table_order| %>
        <div class="p-8">
          <% if table_order.is_active %>
            <h2 class="text-2xl font-bold mb-3">Table <%= table_order.table.table_number %></h2>
            <div class="flex items-center mb-3">
              <div class="w-4/12 font-bold">Food Name</div>
              <div class="w-2/12 font-bold">Customer Name</div>
              <div class="w-2/12 font-bold">Since Ordered</div>
              <div class="w-2/12 font-bold">Until Ready</div>
              <div class="w-2/12 font-bold"></div>
            </div>
          <% end %>
          <% table_order.order_items.select { |item| item.is_served == false}.each do |order_item| %>
            <div class="flex mt-4" data-controller="restaurant-server">
              <div class="w-4/12 flex items-center">
                <% if order_item.is_prepared %>
                  <span class="bg-green-500 mr-3 px-3 py-2 text-white text-sm font-semibold rounded-lg">Ready</span>
                <% end %>
                <%= order_item.menu_item.name %>
              </div>
              <div class="w-2/12 flex items-center"><%= order_item.table_customer.name %></div>
              <div class="w-2/12 flex items-center" data-restaurant-server-target="ordered"><%= ((Time.now - order_item.created_at) / 60).round %> mins</div>
              <div class="w-2/12 flex items-center" data-restaurant-server-target="ready"><%= order_item.menu_item.prepare_time - ((Time.now - order_item.created_at) / 60).round %> mins</div>
              <div class="w-2/12 flex items-center flex justify-end"><%= link_to "Mark as done", served_path(order_item), class: "bg-gray-900 px-8 py-2 text-white text-sm rounded-lg" %></div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

  <% else %>
    <div class="flex justify-end items-center mb-8">
      <%= link_to "Login", new_user_session_path %>
    </div>
    <h1>you cannot access this page</h1>
  <% end %>
</div>

app/views/table_orders/show.html.erb
<div class="page-container pt-8">

  <div class="flex items-center justify-between mb-8">
    <div class="w-24">
      <%= link_to restaurant_path(@table_order.restaurant) do %>
        <i class="fa-solid fa-chevron-left"></i>
      <% end %>
    </div>

    <h2 class="text-2xl">Table <%= @table_order.table.table_number if @table_order.is_active %></h2>


    <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "flex justify-end w-24" %>
  </div>

  <div class="w-full bg-white rounded-lg p-8">
    <div class="flex items-center mb-3">
      <div class="w-4/12 font-bold">Food Name</div>
      <div class="w-2/12 font-bold">Customer Name</div>
      <div class="w-2/12 font-bold">Since Ordered</div>
      <div class="w-2/12 font-bold">Until Ready</div>
      <div class="flex justify-end w-2/12 font-bold">Status</div>
    </div>

    <div class="overflow-auto scroll-container">
      <% @table_order.order_items.each do |order_item| %>
        <% if order_item.is_ordered %>
          <div class="flex mt-4" data-controller="restaurant-server">
            <div class="w-4/12 flex items-center"><%= order_item.menu_item.name %></div>
            <div class="w-2/12 flex items-center"><%= order_item.table_customer.name %></div>
            <div class="w-2/12 flex items-center" data-restaurant-server-target="ordered"><%= ((Time.now - order_item.created_at) / 60).round %> mins</div>
            <div class="w-2/12 flex items-center" data-restaurant-server-target="ready"><%= order_item.menu_item.prepare_time - ((Time.now - order_item.created_at) / 60).round %> mins</div>
            <div class="flex justify-end w-2/12 flex items-center">
              <% if order_item.is_served %>
                <span class="bg-green-500 px-3 py-2 text-white text-sm rounded-lg">served</span>
              <% else %>
                <span class="bg-red-500 px-3 py-2 text-white text-sm rounded-lg">not served</span>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>