config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "restaurants#index"
  get "/restaurants/:id/kitchen", to: "restaurants#kitchen", as: "kitchen"
  get "/restaurants/:restaurant_id/users/:user_id/table_orders", to: "table_orders#server", as: "server"
  get "/order_items/:id/prepared", to: "order_items#prepared!", as: "prepared"
  get "/order_items/:id/served", to: "order_items#served!", as: "served"
  get "/table_customers/:id/ordered", to: "table_customers#ordered!", as: "ordered"
  # get "restaurants/:id/tables/:table_id/table_orders/:table_order_id/checkout", to: "table_orders#checkout", as: "checkout"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/checkout", to: "table_customers#checkout", as: "checkout"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/confirmation", to: "table_customers#confirmation", as: "confirmation"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :join_menus, only: :destroy
  resources :order_items, only: :destroy
  resources :restaurants do
    resources :restaurant_servers
    resources :menu_items
    resources :menus do
      resources :join_menus, only: %i[show new create]
    end
    resources :tables do
      resources :table_orders do
        resources :table_customers do
          resources :order_items
        end
      end
    end
  end
  get "restaurants/:restaurant_id/menus/:id/activated", to: "menus#activated!", as: "activated"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/split_evenly", to: "table_customers#split_evenly", as: "split_evenly"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/split_by_items", to: "table_customers#split_by_items", as: "split_by_items"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/pay_all", to: "table_customers#pay_all", as: "pay_all"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/card_roulette", to: "table_customers#card_roulette", as: "card_roulette"
end

app/models/table_customer.rb
class TableCustomer < ApplicationRecord
  has_many :order_items
  belongs_to :table_order
  has_one :table, through: :table_order
  has_one :restaurant, through: :table

  validates :name, presence: true
end

app/controllers/table_customers_controller.rb
class TableCustomersController < ApplicationController
  before_action :set_table_customer, only: [:show, :edit, :update, :destroy,:split_evenly, :split_by_items, :checkout, :pay_all, :card_roulette, :ordered!, :confirmation]
  before_action :set_restaurant, only: [:index, :show, :new, :create, :split_evenly, :split_by_items, :checkout, :pay_all, :card_roulette]
  before_action :set_table, only: [:index, :show, :new, :create, :checkout, :split_evenly, :split_by_items, :pay_all, :card_roulette]
  before_action :set_table_order, only: [:index, :show, :new, :create, :checkout, :split_evenly, :split_by_items, :pay_all, :card_roulette]

  def index
    @table_customers = TableCustomer.all
  end

  def show
  end

  def new
    @table_customer = TableCustomer.new
  end

  def create
    # Needs work
    @table_customer = TableCustomer.new(table_customer_params)
    @table_customer.is_captain = true if params[:table_customer][:is_captain] == "false"

    @table_order.user = User.where(is_owner: false).sample
    @table_customer.table_order_id = @table_order.id

    @table_customer.table_order = @table_order

    if @table_customer.save
      redirect_to new_restaurant_table_table_order_table_customer_order_item_path(@restaurant, @table, @table_order, @table_customer)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def split_evenly
    number = @table_order.table_customers.count
    splitted_bill = (@table_order.total_price.to_f / number).round(2)
    total_amount = (splitted_bill * 1.125).round(2)

    @table_order.table_customers.each do |customer|
      customer.update(amount_due: splitted_bill.to_f)
      customer.update(total_amount: total_amount.to_f)
    end
    @table_order.update(payment_option: "split_evenly")
    redirect_to checkout_path(@restaurant, @table, @table_order, @table_customer)
  end

  def split_by_items
    total_amount = (@table_customer.amount_due.to_f * 1.125).round(2)
    @table_customer.update(total_amount: total_amount.to_f)
    @table_order.update(payment_option: "split_by_items")
    redirect_to checkout_path(@restaurant, @table, @table_order, @table_customer)
  end

  def pay_all
    @payment_customer = TableCustomer.find(params[:payment_customer_id])
    table_amount = (@table_order.total_price * 1.125).round(2)
    @payment_customer.update(amount_due: @table_order.total_price)
    @payment_customer.update(total_amount: table_amount)
    @table_order.update(payment_option: "pay_all")
    @other_customers = @table_order.table_customers.select { |customer| customer.id != @payment_customer.id }
    unless @other_customers.nil?
      @other_customers.each do |customer|
        customer.update(amount_due: 0.to_f)
        customer.update(total_amount: 0.to_f)
      end
    end

    if @table_customer == @payment_customer
      redirect_to checkout_path(@restaurant, @table, @table_order, @payment_customer)
    else
      redirect_to confirmation_path()
    end
  end

  def card_roulette
    @payment_customer = TableCustomer.find(params[:payment_customer_id])
    table_amount = (@table_order.total_price * 1.125).round(2)
    @payment_customer.update(amount_due: @table_order.total_price.to_f)
    @payment_customer.update(total_amount: table_amount.to_f)
    @table_order.update(payment_option: "card_roulette")
    @other_customers = @table_order.table_customers.select { |customer| customer.id != @payment_customer.id }
    unless @other_customers.nil?
      @other_customers.each do |customer|
        customer.update(amount_due: 0.to_f)
        customer.update(total_amount: 0.to_f)
      end
    end

    if @table_customer == @payment_customer
      redirect_to checkout_path(@restaurant, @table, @table_order, @payment_customer)
    else
      redirect_to confirmation_path()
    end
  end

  def checkout
    # order  = Order.create!(teddy: teddy, teddy_sku: teddy.sku, amount: teddy.price, state: 'pending', user: current_user)
    @payment_customer = TableCustomer.find(params[:id])
    @table_price = @table_customer.total_amount.to_f
    @subtotal = @table_customer.amount_due.to_f
    @service_charge = (@subtotal * 0.125).round(2)
    @tip = (@subtotal * 0.0).round(2)
    @tax = (@subtotal - (@subtotal / 1.2)).round(2)

    # @table_customer.order_items.each do |order|
    #   table_price += order.menu_item.price
    # end
    @restaurant = @table_customer.table_order.restaurant
    session = Stripe::Checkout::Session.create(
      payment_method_types: ['card'],
      line_items: [{
        price_data: {
          currency: 'usd',
          unit_amount: (@table_price * 100).to_i,
          product_data: {
            name: 'Your order',
            description: 'Food',
            images: ['https://example.com/t-shirt.png'],
          },
        },
        quantity: 1
      }],
      mode: 'payment',
      success_url: "http://www.billy-961.com/restaurants/#{@restaurant.id}/tables/#{@table.id}/table_orders/#{@table_order.id}/table_customers/#{@table_customer.id}/confirmation",
      cancel_url: "http://www.billy-961.com/restaurants/#{@restaurant.id}/tables/#{@table.id}/table_orders/#{@table_order.id}/table_customers/#{@table_customer.id}/checkout",
    )

    @table_customer.update(checkout_session_id: session.id)
    # redirect_to checkout_path(@restaurant, @table, @table_order)
  end

  def confirmation
    @restaurant = Restaurant.find(params[:restaurant_id])
    @table_order = TableOrder.find(params[:table_order_id])
    @table = Table.find(params[:table_id])
    @table_order.update(is_active: false)
    @table.update(is_active: false)
  end

  def ordered!
    @table_order = @table_customer.table_order
    @table_customer.order_items.where(is_ordered: false).each do |item|
      item.update(is_ordered: true)
      customer_new_amount = @table_customer.amount_due.to_f + item.menu_item.price
      table_order_new_amount = @table_order.total_price.to_f + item.menu_item.price
      @table_customer.update(amount_due: customer_new_amount.round(2))
      @table_order.update(total_price: table_order_new_amount.round(2))
    end

    redirect_to restaurant_table_table_order_table_customer_order_items_path(
      @table_customer.restaurant,
      @table_customer.table,
      @table_customer.table_order,
      @table_customer
    )
  end

  private

  def set_table_customer
    @table_customer = TableCustomer.find(params[:id])
  end

  def set_table_order
    @table_order = TableOrder.find(params[:table_order_id])
  end

  def set_table
    @table = Table.find(params[:table_id])
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def table_customer_params
    # Needs work
    params.require(:table_customer).permit(:name, :is_captain, :is_paid)
  end
end

app/views/table_customers/_show.html.erb
<div class="customer-container">
  <div class="w-full h-40 bg-gray-300 flex flex-col p-3">
    <div class="self-end">
      <div class="flex -space-x-2 overflow-hidden">
        <%# .each here %>
        <img class="inline-block h-8 w-8 rounded-full ring-2 ring-white" src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
        <img class="inline-block h-8 w-8 rounded-full ring-2 ring-white" src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
        <img class="inline-block h-8 w-8 rounded-full ring-2 ring-white" src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80" alt="">
        <img class="inline-block h-8 w-8 rounded-full ring-2 ring-white" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
      </div>
    </div>
    <% active_menu = Menu.find_by(is_active: true) %>
    <div>
      <h1 class="text-3xl font-bold mt-3"><%= active_menu.name %></h1>
    </div>
    <div class="flex gap-2 mt-4 text-sm">
      <%# .each here %>
      <h5 class="px-2 py-1 active1">All</h5>
      <h5 class="px-2 py-1">Starter</h5>
      <h5 class="px-2 py-1">Main Course</h5>
      <h5 class="px-2 py-1">Dessert</h5>
    </div>
  </div>
  <div class="p-3">
    <h2 class="mt-2 text-lg font-bold">Starter</h2>
      <%# .each here %>
    <% active_menu.menu_items.each do |menu_item| %>
      <div class="w-full flex items-center mt-2">
        <div class="mr-5">
          <% if item.photo.attached? %>
            <%= cl_image_tag item.photo.key, height: 150, width: 150, crop: :fill, class: "d-block rounded-lg" %>
          <% else %>
            <img src=<%= "https://source.unsplash.com/random/75x75/?restaurant-#{menu_item.name}" %> class="d-block rounded-lg" alt="restaurant image">
          <% end %>
        </div>
        <div>
          <p class="font-bold text-sm"><%= menu_item.name %></p>
          <p class="text-sm">$<%= menu_item.price %></p>
        </div>
      </div>
    <% end %>

    <h2 class="mt-4 text-lg font-bold">Main Course</h2>
      <%# .each here %>
      <div class="w-full flex items-center mt-2">
        <div class="mr-5">
          <img src=<%= "https://source.unsplash.com/random/75x75/?restaurant-4" %> class="d-block rounded-lg" alt="restaurant image">
        </div>
        <div>
          <p class="font-bold text-sm">This is a Food Item</p>
          <p class="text-sm">$10</p>
        </div>
      </div>

      <div class="w-full flex items-center mt-2">
        <div class="mr-5">
          <img src=<%= "https://source.unsplash.com/random/75x75/?restaurant-5" %> class="d-block rounded-lg" alt="restaurant image">
        </div>
        <div>
          <p class="font-bold text-sm">This is a Food Item</p>
          <p class="text-sm">$10</p>
        </div>
      </div>

      <div class="w-full flex items-center mt-2">
        <div class="mr-5">
          <img src=<%= "https://source.unsplash.com/random/75x75/?restaurant-6" %> class="d-block rounded-lg" alt="restaurant image">
        </div>
        <div>
          <p class="font-bold text-sm">This is a Food Item</p>
          <p class="text-sm">$10</p>
        </div>
      </div>

    <h2 class="mt-4 text-lg font-bold">Dessert</h2>
      <%# .each here %>
    <div class="w-full flex items-center mt-2">
      <div class="mr-5">
        <img src=<%= "https://source.unsplash.com/random/75x75/?restaurant-7" %> class="d-block rounded-lg" alt="restaurant image">
      </div>
      <div>
        <p class="font-bold text-sm">This is a Food Item</p>
        <p class="text-sm">$10</p>
      </div>
    </div>

    <div class="w-full flex items-center mt-2">
      <div class="mr-5">
        <img src=<%= "https://source.unsplash.com/random/75x75/?restaurant-8" %> class="d-block rounded-lg" alt="restaurant image">
      </div>
      <div>
        <p class="font-bold text-sm">This is a Food Item</p>
        <p class="text-sm">$10</p>
      </div>
    </div>


    <div class="w-full flex justify-center">
      <button class="bg-black text-white px-12 py-2 rounded-lg fixed bottom-9">See your order</button>
    </div>
  </div>
</div>

app/views/table_customers/checkout.html.erb
<div class="customer-container">
  <div class="w-full h-28 bg-gray-300 flex items-end p-4">
    <div class="flex">
      <h1 class="text-3xl font-bold">Your Payment</h1>
    </div>
  </div>
  <div class="p-3">
    <% @table_captain = @table_order.table_customers.find{ |customer| customer.is_captain == true }.name %>
    <% if @table_order.payment_option == "split_evenly" %>
      <h2 class="text-xl font-bold mt-4"><%= @table_captain %> chose to split evenly</h2>
      <div class="flex justify-between items-center mt-10">
        <h3>Your Table Subtotal</h3>
        <p>$<%= @table_order.total_price %></p>
      </div>
      <div class="flex justify-between items-center mt-1">
        <h3>Number of Diners</h3>
        <p><%= @table_order.table_customers.count %></p>
      </div>
      <div class="flex justify-between items-center mt-1">
        <h3 class="font-bold">Your Portion</h3>
        <p class="font-bold">$<%= @table_customer.amount_due %></p>
      </div>
    <% elsif @table_order.payment_option == "split_by_items" %>
      <h2 class="text-xl font-bold mt-4"><%= @table_captain %> chose to split by items</h2>
      <h3 class="text-xl mt-10">Your Items</h3>
      <% @table_customer.order_items.each do |item| %>
        <div class="flex justify-between items-center mt-2">
          <h3><%= item.menu_item.name %></h3>
          <p>$<%= item.menu_item.price %></p>
        </div>
      <% end %>
    <% elsif @table_order.payment_option == "card_roulette" %>
      <h2 class="text-xl font-bold mt-4">Congrats, <%= @payment_customer.name %>! You won credit card roulette. You must now pay the tab.</h2>
    <% elsif @table_order.payment_option == "pay_all" %>
      <% if @table_captain == @payment_customer %>
        <h2 class="text-xl font-bold mt-4"><%= @payment_customer.name %>, you are paying the tab.</h2>
      <% else %>
        <h2 class="text-xl font-bold mt-4"><%= @payment_customer.name %>, you were selected by <%= @table_captain %> to pay the tab.</h2>
      <% end %>
    <% end %>

    <h2 class="font-bold mt-12">Would you like to leave a tip?</h2>
    <div class="flex justify-between items-center mt-2">
      <div class="bg-gray-200 px-3 py-1 rounded-lg">5%</div>
      <div class="bg-gray-200 px-3 py-1 rounded-lg">10%</div>
      <div class="bg-gray-200 px-3 py-1 rounded-lg">15%</div>
      <div class="bg-gray-200 px-3 py-1 rounded-lg">20%</div>
      <div class="bg-gray-200 px-3 py-1 rounded-lg">25%</div>
    </div>
    <div class="mt-12">
      <div class="flex justify-between items-center mt-1">
        <h3>subtotal</h3>
        <p><%= number_to_currency(@subtotal.to_f) %></p>
      </div>
      <div class="flex justify-between items-center mt-1">
        <h3>service charge</h3>
        <p><%= number_to_currency(@service_charge.to_f) %></p>
      </div>
      <div class="flex justify-between items-center mt-1">
        <h3>tip</h3>
        <p><%= number_to_currency(@tip.to_f) %></p>
      </div>
      <div class="flex justify-between items-center mt-1">
        <h3>tax</h3>
        <p><%= number_to_currency(@tax.to_f) %></p>
      </div>
      <div class="flex justify-between items-center mt-4">
        <h3 class="text-xl font-bold">Total Due</h3>
        <p class="text-xl font-bold"><%= number_to_currency(@table_price.to_f) %></p>
      </div>
    </div>
    <div class="w-full flex justify-center mt-12">
      <button class="bg-black text-white px-5 py-2 rounded-lg" id="pay">Go to payment</button>
    </div>
  </div>
  <script src="https://js.stripe.com/v3/"></script>
  <script>
    paymentButton = document.getElementById('pay');
    paymentButton.addEventListener('click', () => {
      const stripe = Stripe('<%= ENV['STRIPE_PUBLISHABLE_KEY'] %>');
      stripe.redirectToCheckout({
        sessionId: '<%= @table_customer.checkout_session_id %>'
      });
    });
  </script>
</div>

app/views/table_customers/confirmation.html.erb
<div class="h-screen flex flex-col justify-center items-center gap-5 p-5">
  <p class="text-4xl text-center"><%= @restaurant.name %></P>
  <i class="tick-icon fa-solid fa-circle-check text-7xl"></i>
  <% if @table_customer.total_amount.zero? %>
    <h1 class="text-4xl text-center font-bold">Good to go!</h1>
  <% else %>
    <h1 class="text-4xl text-center font-bold">Payment success!</h1>
  <% end %>
  <p class="text-xl text-center">Thank you for dining with us. We hope to see you again soon</p>
  <p>Share Your Experience</p>
  <div class="flex gap-5">
    <i class="fa-brands fa-facebook text-2xl"></i>
    <i class="fa-brands fa-twitter text-2xl"></i>
    <i class="fa-brands fa-instagram text-2xl"></i>
  </div>
</div>

app/views/table_customers/new.html.erb
<div class="landing-background w-screen h-screen">
  <div class="customer-container-landing h-full flex flex-col justify-between">
    <div class="w-full h-48"></div>
    <h2 class="flex w-full justify-center items-center text-2xl font-bold"><%= @restaurant.name %></h2>

      <%= simple_form_for [@restaurant, @table, @table_order, @table_customer] do |f| %>
        <%  if @table_order.table_customers.empty? %>
          <%= f.input :is_captain, as: :hidden, default: true %>
        <%  end %>
        <%= f.input :is_paid, as: :hidden, default: false %>
        <div class="flex flex-col justify-end w-full h-48">
          <div class="w-full">
            <%= f.input :name,
                        label: false,
                        placeholder: "Name" %>
          </div>
          <%= f.submit "Go", class: "flex w-full justify-center items-center h-10 rounded-lg bg-black text-lg font-bold text-white" %>
        </div>
      <% end %>
  </div>
</div>

app/views/table_customers/show.html.erb
<div class="customer-container">
  <div class="w-full h-28 bg-gray-300 flex items-end p-4">
    <div class="flex items-center gap-3">
      <%= link_to new_restaurant_table_table_order_table_customer_order_item_path(@restaurant, @table, @table_order, @table_customer) do %>
      <i class="fa-solid fa-chevron-left text-xl"></i>
      <% end %>
      <h1 class="text-3xl font-bold"><%= @table_customer.name %></h1>
    </div>
  </div>

  <div class="px-4">
    <% basket_items = @table_customer.order_items.where(is_ordered: false) %>
    <% basket_items.each do |item| %>
      <div class="w-full flex items-center mt-4">
        <div class="mr-5">
          <% if item.menu_item.photo.attached? %>
            <%= cl_image_tag item.menu_item.photo.key, height: 75, width: 75, crop: :fill, class: "d-block rounded-lg" %>
          <% else %>
            <img src=<%= "https://source.unsplash.com/random/75x75/?restaurant-#{item}" %> class="d-block rounded-lg" alt="restaurant image">
          <% end %>
        </div>
        <div class="w-6/12">
          <p class="font-bold text-sm"><%= item.menu_item.name %></p>
          <p class="text mt-2"><%= number_to_currency(item.menu_item.price.to_f) %></p>
        </div>
        <div class="flex items-center gap-3">
          <%= link_to order_item_path(item), data: { turbo_method: :delete } do %>
            <i class="fa-solid fa-minus text-gray-400 text-lg"></i>
          <% end %>
          <p class="text-xl">1</p>
          <i class="fa-solid fa-plus text-gray-400 text-lg"></i>
        </div>
      </div>
    <% end %>

    <div class="w-full flex justify-between mt-3 mb-16">
      <h1 class="text-xl font-bold">Total amount</h1>
      <% sum = 0 %>
      <% basket_items.each do |item| %>
        <% sum += item.menu_item.price %>
      <% end %>
      <h1 class="text-xl font-bold"><%= number_to_currency(sum.to_f) %></h1>
    </div>

    <div class="w-full flex justify-center">
      <% if basket_items.count.zero? %>
        <%= link_to "Back to Table order", restaurant_table_table_order_table_customer_order_items_path(@restaurant, @table, @table_order, @table_customer), class: "bg-black text-white px-12 py-2 rounded-lg fixed bottom-5" %>
      <% else %>
        <%= link_to "Place your order", ordered_path(@table_customer), class: "bg-black text-white px-12 py-2 rounded-lg fixed bottom-5" %>
      <% end %>
    </div>
  </div>
</div>