config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "restaurants#index"
  get "/restaurants/:id/kitchen", to: "restaurants#kitchen", as: "kitchen"
  get "/restaurants/:restaurant_id/users/:user_id/table_orders", to: "table_orders#server", as: "server"
  get "/order_items/:id/prepared", to: "order_items#prepared!", as: "prepared"
  get "/order_items/:id/served", to: "order_items#served!", as: "served"
  get "/table_customers/:id/ordered", to: "table_customers#ordered!", as: "ordered"
  # get "restaurants/:id/tables/:table_id/table_orders/:table_order_id/checkout", to: "table_orders#checkout", as: "checkout"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/checkout", to: "table_customers#checkout", as: "checkout"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/confirmation", to: "table_customers#confirmation", as: "confirmation"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :join_menus, only: :destroy
  resources :order_items, only: :destroy
  resources :restaurants do
    resources :restaurant_servers
    resources :menu_items
    resources :menus do
      resources :join_menus, only: %i[show new create]
    end
    resources :tables do
      resources :table_orders do
        resources :table_customers do
          resources :order_items
        end
      end
    end
  end
  get "restaurants/:restaurant_id/menus/:id/activated", to: "menus#activated!", as: "activated"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/split_evenly", to: "table_customers#split_evenly", as: "split_evenly"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/split_by_items", to: "table_customers#split_by_items", as: "split_by_items"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/pay_all", to: "table_customers#pay_all", as: "pay_all"
  get "restaurants/:restaurant_id/tables/:table_id/table_orders/:table_order_id/table_customers/:id/card_roulette", to: "table_customers#card_roulette", as: "card_roulette"
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :menus
  has_many :menu_items
  has_many :tables
  has_many :table_orders, through: :tables
  has_many :table_customers, through: :table_orders
  has_many :order_items, through: :table_customers
  has_many :restaurant_servers
  has_many :users, through: :restaurant_servers
  has_one_attached :photo

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show kitchen edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @referer = request.referer
  end

  def kitchen
    @food_tickets = @restaurant.order_items.select { |item| item.is_ordered == true && item.is_prepared == false }.sort_by(&:id)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = User.find_by(is_owner: true)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @restaurant = Restaurant.new
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :theme_color, :photo)
  end
end

app/views/restaurants/_form.html.erb
<%= simple_form_for [restaurant] do |f| %>
  <div>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :photo, as: :file %>
  </div>
  <div class="flex justify-start items-center pt-8">
    <div class="flex justify-center items-center h-10 rounded-lg bg-black">
      <%= f.submit "Create", class: "text-xl mx-8 text-white" %>
    </div>
  </div>
<% end %>

app/views/restaurants/_info.html.erb
<div class="flex justify-between">
  <div class="my-auto w-4/12">
    <% if restaurant.photo.attached? %>
      <%= cl_image_tag restaurant.photo.key, width: 336, height: 336, crop: :fill, class: "d-block rounded-lg" %>
    <% else %>
      <img src="https://res.cloudinary.com/dmlfirids/image/upload/v1663060224/restaurant/restaurant1.jpg", style="width: 336px; height:336px" class="d-block rounded-lg" alt="restaurant image">
    <% end %>
  </div>

  <div class="flex flex-col w-8/12">
    <div class="w-full bg-white rounded-lg p-8">
      <h2 class="text-xl font-bold">Info</h2>
      <div class="flex mt-3">
        <h4 class="font-bold">Name</h4>
        <p class="ml-5"><%= restaurant.name %></p>
      </div>
      <div class="flex mt-3">
        <h4 class="font-bold">Phone</h4>
        <p class="ml-5"><%= restaurant.phone_number %></p>
      </div>
      <div class="flex mt-3">
        <h4 class="font-bold">Address</h4>
        <p class="ml-5"><%= restaurant.address %></p>
      </div>
    </div>

    <div class="flex mt-8">
      <div class="w-52 bg-stone-300 rounded-l-lg">
        <h2 class="text-xl font-bold z-10 m-8">Theme</h2>
      </div>
      <div class="w-52 bg-stone-500"></div>
      <div class="w-52 bg-stone-700"></div>
      <div class="w-52 bg-stone-900 rounded-r-lg"></div>
    </div>
  </div>
</div>

<div class="mt-8 flex justify-between w-full bg-white rounded-lg">

  <div class="w-full m-8">
    <%= link_to restaurant_tables_path(restaurant) do %>
      <h2 class="text-xl font-bold">Tables</h2>
    <% end %>

    <div class=" mt-3 flex flex-col flex-wrap h-24 w-full justify-between content-start overflow-auto">
      <% restaurant.tables.each do |table| %>

        <% table_order = table.table_orders.select(&:is_active).first %>
        <% if table_order.nil? %>
          <div class="flex justify-center items-center w-10 h-10 rounded-full border mr-3">
            <h4 class="font-bold"><%= table.table_number %></h4>
          </div>
        <% else %>
          <%= link_to restaurant_table_table_order_path(restaurant, table, table_order) do %>
            <div class="flex justify-center items-center w-10 h-10 rounded-full border-t border-b border-l border-r border-black mr-3 hover:bg-black hover:text-white">
              <h4 class="font-bold"><%= table.table_number %></h4>
            </div>
          <% end %>
        <% end %>

      <% end %>
    </div>
  </div>

  <div class="flex justify-center items-center bg-white rounded-tr-lg rounded-br-lg p-8 border-l border-black z-10">
    <%= link_to new_restaurant_table_path(restaurant) do %>
      <div class="flex justify-center items-center w-10 h-10 rounded-full bg-black">
        <i class="fa-solid fa-plus text-white"></i>
      </div>
    <% end %>
  </div>
</div>


<div class="mt-8 flex justify-between w-full bg-white rounded-lg">

  <div class="m-8">
    <h2 class="text-xl font-bold">Servers</h2>
    <div class="mt-3 flex h-10 w-full justify-start items-center overflow-auto">
      <% restaurant.users.each do |user| %>

        <% if user.table_orders.select(&:is_active).empty? %>
          <div class="flex justify-center items-center h-8 rounded-lg border border-black p-3 mr-3">
            <h4 class="font-bold"><%= user.first_name %></h4>
          </div>
        <% else %>
          <%= link_to server_path(restaurant, user.id) do %>
            <div class="flex justify-center items-center h-8 rounded-lg border-t border-b border-l border-r border-black p-3 mr-3 hover:bg-black hover:text-white">
              <h4 class="font-bold"><%= user.first_name %></h4>
            </div>
          <% end %>
        <% end %>

      <% end %>
    </div>
  </div>

  <div class="flex justify-center items-center bg-white rounded-tr-lg rounded-br-lg p-8 border-l border-black z-10">
    <div class="flex justify-center items-center w-10 h-10 rounded-full bg-black">
      <i class="fa-solid fa-plus text-white"></i>
    </div>
  </div>
</div>

<%# Kitchen link %>
<div class="mt-8 flex justify-between w-full bg-white rounded-lg">
  <div class="m-8">
    <h2 class="text-xl font-bold"><%= link_to "Kitchen", kitchen_path(restaurant) %></h2>
  </div>
</div>

app/views/restaurants/_list.html.erb
<% restaurants.each do |restaurant| %>
  <%= render restaurant %>
<% end %>

app/views/restaurants/_restaurant.html.erb
<%= link_to restaurant_path(restaurant) do %>
  <div class="flex items-center justify-center p-8 bg-white rounded-lg">
    <div>
      <% if restaurant.photo.attached? %>
        <%= cl_image_tag restaurant.photo.key, width: 200, height: 200, crop: :fill, class: "d-block rounded-lg" %>
      <% else %>
        <img src="https://res.cloudinary.com/dmlfirids/image/upload/v1663060224/restaurant/restaurant1.jpg", style="height:200px; width: 200px" class="d-block rounded-lg" alt="restaurant image">
      <% end %>
      <h4 class="font-bold mt-3 text-center"><%= restaurant.name %></h4>
    </div>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<div class="page-container h-screen py-8">
  <div class="h-full flex flex-col justify-between">

    <div class="h-10 flex items-center justify-center mb-8">
      <h2 class="text-xl font-bold">My Restaurants</h2>
    </div>

    <div class="flex flex-wrap justify-center gap-10 h-max">
      <%= render "restaurants/list", restaurants: @restaurants %>
    </div>

    <div class="flex justify-center items-center bottom-0 my-8">
      <%= link_to new_restaurant_path do %>
        <div class="flex justify-center items-center w-10 h-10 rounded-full bg-black">
          <i class="fa-solid fa-plus text-white"></i>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/kitchen.html.erb
<div class="page-container py-8">
  <div class="h-10 flex items-center justify-between mb-8">
    <%= link_to restaurant_path(@restaurant) do %>
      <div class="flex items-center w-24">
        <i class="fa-solid fa-chevron-left"></i>
      </div>
    <% end %>
    <h2 class="text-xl font-bold">Kitchen Tickets</h2>
    <div class="w-24"></div>
  </div>
  <div class="flex flex-wrap justify-around">
    <% @food_tickets.each do |food_ticket| %>
      <div class="w-80 p-8 m-3 bg-white rounded-lg">
        <%= render "order_items/show", item: food_ticket %>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="page-container pt-8">
  <div class="flex items-center justify-between mb-8">
    <div class="w-48">
      <%= link_to restaurants_path do %>
        <i class="fa-solid fa-chevron-left"></i>
      <% end %>
    </div>
    <h2 class="text-xl font-bold">New Restaurant</h2>
    <div class="w-48"></div>
  </div>
  <%= render "restaurants/form", restaurant: @restaurant %>
</div>

app/views/restaurants/show.html.erb
<div class="page-container pt-8" data-controller="nav-links">
  <div class="flex justify-between items-center">
    <div class="flex justify-start w-48">
        <%= link_to restaurants_path do %>
          <div class="flex items-center gap-3">
            <i class="fa-solid fa-chevron-left"></i>
            <h2 class="text-xl font-bold">My Restaurants</h2>
          </div>
        <% end %>
    </div>

    <div class="flex justify-center items-center">
      <ul class="nav nav-pills" id="pills-tab" role="tablist">
      <% if @referer && @referer.include?('menu') %>
        <li class="nav-item" role="presentation">
          <button class="btn btn-outline-dark" id="pills-restaurant-tab" data-bs-toggle="pill" data-bs-target="#pills-restaurant" type="button" role="tab" aria-controls="pills-restaurant" aria-selected="true">RESTAURANT INFO</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="btn btn-outline-dark active" id="pills-menu-tab" data-bs-toggle="pill" data-bs-target="#pills-menu" type="button" role="tab" aria-controls="pills-menu" aria-selected="false">MENU INFO</button>
        </li>
        <% else %>
        <li class="nav-item" role="presentation">
          <button class="btn btn-outline-dark active" id="pills-restaurant-tab" data-bs-toggle="pill" data-bs-target="#pills-restaurant" type="button" role="tab" aria-controls="pills-restaurant" aria-selected="true">RESTAURANT INFO</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="btn btn-outline-dark" id="pills-menu-tab" data-bs-toggle="pill" data-bs-target="#pills-menu" type="button" role="tab" aria-controls="pills-menu" aria-selected="false">MENU INFO</button>
        </li>
        <% end %>
      </ul>
    </div>

    <div class="flex justify-end w-48">
      <%= link_to destroy_user_session_path, data: {turbo_method: :delete} do %>
        <div class="flex justify-center items-center h-8 rounded-lg border-t border-b border-l border-r border-black p-3 hover:bg-black hover:text-white">
          <h4><%= "Logout" %></h4>
        </div>
      <% end %>
    </div>
  </div>

  <div class="tab-content" id="pills-tabContent">
    <% if @referer && @referer.include?('menu') %>
      <div class="py-8 tab-pane fade show" id="pills-restaurant" role="tabpanel" aria-labelledby="pills-restaurant-tab">
        <%= render "restaurants/info", restaurant: @restaurant %>
      </div>
      <div class="py-8 tab-pane fade show active" id="pills-menu" role="tabpanel" aria-labelledby="pills-menu-tab">
        <div class="flex gap-5">
          <%= render "menus/index", restaurant: @restaurant, menus: @restaurant.menus %>
          <%= render "menu_items/index", restaurant: @restaurant %>
        </div>
      </div>
    <% else %>
      <div class="py-8 tab-pane fade show active" id="pills-restaurant" role="tabpanel" aria-labelledby="pills-restaurant-tab">
        <%= render "restaurants/info", restaurant: @restaurant %>
      </div>
      <div class="py-8 tab-pane fade" id="pills-menu" role="tabpanel" aria-labelledby="pills-menu-tab">
        <div class="flex gap-5">
          <%= render "menus/index", restaurant: @restaurant, menus: @restaurant.menus %>
          <%= render "menu_items/index", restaurant: @restaurant %>
        </div>
      </div>
    <% end %>
  </div>

</div>